# Generated by Django 5.0.6 on 2024-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={
                "db_table": "auth_group",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_group_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "auth_permission",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField()),
                ("username", models.CharField(max_length=150, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=254)),
                ("is_staff", models.IntegerField()),
                ("is_active", models.IntegerField()),
                ("date_joined", models.DateTimeField()),
            ],
            options={
                "db_table": "auth_user",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserGroups",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_groups",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AuthUserUserPermissions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "auth_user_user_permissions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cc2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2019_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2019-03-09", null=True
                    ),
                ),
                (
                    "number_2019_04_12",
                    models.FloatField(blank=True, db_column="2019-04-12", null=True),
                ),
                (
                    "number_2019_05_09",
                    models.FloatField(blank=True, db_column="2019-05-09", null=True),
                ),
                (
                    "number_2019_06_04",
                    models.FloatField(blank=True, db_column="2019-06-04", null=True),
                ),
                (
                    "number_2019_06_14",
                    models.FloatField(blank=True, db_column="2019-06-14", null=True),
                ),
                (
                    "number_2019_06_28",
                    models.FloatField(blank=True, db_column="2019-06-28", null=True),
                ),
                (
                    "number_2019_07_11",
                    models.FloatField(blank=True, db_column="2019-07-11", null=True),
                ),
                (
                    "number_2019_07_18",
                    models.FloatField(blank=True, db_column="2019-07-18", null=True),
                ),
            ],
            options={
                "db_table": "CC2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cc2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2020_02_29",
                    models.BigIntegerField(
                        blank=True, db_column="2020-02-29", null=True
                    ),
                ),
                (
                    "number_2020_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-09", null=True
                    ),
                ),
                (
                    "number_2020_03_20",
                    models.FloatField(blank=True, db_column="2020-03-20", null=True),
                ),
                (
                    "number_2020_04_01",
                    models.FloatField(blank=True, db_column="2020-04-01", null=True),
                ),
                (
                    "number_2020_04_07",
                    models.FloatField(blank=True, db_column="2020-04-07", null=True),
                ),
                (
                    "number_2020_04_16",
                    models.FloatField(blank=True, db_column="2020-04-16", null=True),
                ),
                (
                    "number_2020_04_23",
                    models.FloatField(blank=True, db_column="2020-04-23", null=True),
                ),
                (
                    "number_2020_04_30",
                    models.FloatField(blank=True, db_column="2020-04-30", null=True),
                ),
                (
                    "number_2020_05_07",
                    models.FloatField(blank=True, db_column="2020-05-07", null=True),
                ),
                (
                    "number_2020_05_14",
                    models.FloatField(blank=True, db_column="2020-05-14", null=True),
                ),
                (
                    "number_2020_05_20",
                    models.FloatField(blank=True, db_column="2020-05-20", null=True),
                ),
                (
                    "number_2020_05_28",
                    models.FloatField(blank=True, db_column="2020-05-28", null=True),
                ),
                (
                    "number_2020_06_04",
                    models.FloatField(blank=True, db_column="2020-06-04", null=True),
                ),
                (
                    "number_2020_06_11",
                    models.FloatField(blank=True, db_column="2020-06-11", null=True),
                ),
                (
                    "number_2020_06_18",
                    models.FloatField(blank=True, db_column="2020-06-18", null=True),
                ),
                (
                    "number_2020_06_24",
                    models.FloatField(blank=True, db_column="2020-06-24", null=True),
                ),
                (
                    "number_2020_07_02",
                    models.FloatField(blank=True, db_column="2020-07-02", null=True),
                ),
                (
                    "number_2020_07_07",
                    models.FloatField(blank=True, db_column="2020-07-07", null=True),
                ),
            ],
            options={
                "db_table": "CC2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cc2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2021_02_27",
                    models.BigIntegerField(
                        blank=True, db_column="2021-02-27", null=True
                    ),
                ),
                (
                    "number_2021_03_10",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-10", null=True
                    ),
                ),
                (
                    "number_2021_03_26",
                    models.FloatField(blank=True, db_column="2021-03-26", null=True),
                ),
                (
                    "number_2021_04_07",
                    models.FloatField(blank=True, db_column="2021-04-07", null=True),
                ),
                (
                    "number_2021_04_19",
                    models.FloatField(blank=True, db_column="2021-04-19", null=True),
                ),
                (
                    "number_2021_04_29",
                    models.FloatField(blank=True, db_column="2021-04-29", null=True),
                ),
                (
                    "number_2021_05_05",
                    models.FloatField(blank=True, db_column="2021-05-05", null=True),
                ),
                (
                    "number_2021_05_13",
                    models.FloatField(blank=True, db_column="2021-05-13", null=True),
                ),
                (
                    "number_2021_05_20",
                    models.FloatField(blank=True, db_column="2021-05-20", null=True),
                ),
                (
                    "number_2021_05_27",
                    models.FloatField(blank=True, db_column="2021-05-27", null=True),
                ),
                (
                    "number_2021_06_02",
                    models.FloatField(blank=True, db_column="2021-06-02", null=True),
                ),
                (
                    "number_2021_06_10",
                    models.FloatField(blank=True, db_column="2021-06-10", null=True),
                ),
                (
                    "number_2021_06_17",
                    models.FloatField(blank=True, db_column="2021-06-17", null=True),
                ),
                (
                    "number_2021_06_24",
                    models.FloatField(blank=True, db_column="2021-06-24", null=True),
                ),
                (
                    "number_2021_06_30",
                    models.FloatField(blank=True, db_column="2021-06-30", null=True),
                ),
                (
                    "number_2021_07_09",
                    models.FloatField(blank=True, db_column="2021-07-09", null=True),
                ),
                (
                    "number_2021_07_14",
                    models.FloatField(blank=True, db_column="2021-07-14", null=True),
                ),
                (
                    "number_2021_07_19",
                    models.FloatField(blank=True, db_column="2021-07-19", null=True),
                ),
            ],
            options={
                "db_table": "CC2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cc2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2022_03_15",
                    models.BigIntegerField(
                        blank=True, db_column="2022-03-15", null=True
                    ),
                ),
                (
                    "number_2022_03_31",
                    models.FloatField(blank=True, db_column="2022-03-31", null=True),
                ),
                (
                    "number_2022_04_08",
                    models.FloatField(blank=True, db_column="2022-04-08", null=True),
                ),
                (
                    "number_2022_04_27",
                    models.FloatField(blank=True, db_column="2022-04-27", null=True),
                ),
                (
                    "number_2022_05_06",
                    models.FloatField(blank=True, db_column="2022-05-06", null=True),
                ),
                (
                    "number_2022_05_11",
                    models.FloatField(blank=True, db_column="2022-05-11", null=True),
                ),
                (
                    "number_2022_05_21",
                    models.FloatField(blank=True, db_column="2022-05-21", null=True),
                ),
                (
                    "number_2022_05_26",
                    models.FloatField(blank=True, db_column="2022-05-26", null=True),
                ),
                (
                    "number_2022_06_03",
                    models.FloatField(blank=True, db_column="2022-06-03", null=True),
                ),
                (
                    "number_2022_06_08",
                    models.FloatField(blank=True, db_column="2022-06-08", null=True),
                ),
                (
                    "number_2022_06_17",
                    models.FloatField(blank=True, db_column="2022-06-17", null=True),
                ),
                (
                    "number_2022_06_23",
                    models.FloatField(blank=True, db_column="2022-06-23", null=True),
                ),
                (
                    "number_2022_06_30",
                    models.FloatField(blank=True, db_column="2022-06-30", null=True),
                ),
                (
                    "number_2022_07_08",
                    models.FloatField(blank=True, db_column="2022-07-08", null=True),
                ),
                (
                    "number_2022_07_13",
                    models.FloatField(blank=True, db_column="2022-07-13", null=True),
                ),
            ],
            options={
                "db_table": "CC2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cc2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2023_03_04",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-04", null=True
                    ),
                ),
                (
                    "number_2023_03_08",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-08", null=True
                    ),
                ),
                (
                    "number_2023_03_14",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-14", null=True
                    ),
                ),
                (
                    "number_2023_03_20",
                    models.FloatField(blank=True, db_column="2023-03-20", null=True),
                ),
                (
                    "number_2023_03_25",
                    models.FloatField(blank=True, db_column="2023-03-25", null=True),
                ),
                (
                    "number_2023_04_01",
                    models.FloatField(blank=True, db_column="2023-04-01", null=True),
                ),
                (
                    "number_2023_04_11",
                    models.FloatField(blank=True, db_column="2023-04-11", null=True),
                ),
                (
                    "number_2023_04_23",
                    models.FloatField(blank=True, db_column="2023-04-23", null=True),
                ),
                (
                    "number_2023_04_26",
                    models.FloatField(blank=True, db_column="2023-04-26", null=True),
                ),
                (
                    "number_2023_05_01",
                    models.FloatField(blank=True, db_column="2023-05-01", null=True),
                ),
                (
                    "number_2023_05_08",
                    models.FloatField(blank=True, db_column="2023-05-08", null=True),
                ),
                (
                    "number_2023_05_17",
                    models.FloatField(blank=True, db_column="2023-05-17", null=True),
                ),
                (
                    "number_2023_05_24",
                    models.FloatField(blank=True, db_column="2023-05-24", null=True),
                ),
                (
                    "number_2023_05_31",
                    models.FloatField(blank=True, db_column="2023-05-31", null=True),
                ),
                (
                    "number_2023_06_06",
                    models.FloatField(blank=True, db_column="2023-06-06", null=True),
                ),
                (
                    "number_2023_06_12",
                    models.FloatField(blank=True, db_column="2023-06-12", null=True),
                ),
                (
                    "number_2023_06_21",
                    models.FloatField(blank=True, db_column="2023-06-21", null=True),
                ),
                (
                    "number_2023_06_28",
                    models.FloatField(blank=True, db_column="2023-06-28", null=True),
                ),
                (
                    "number_2023_07_05",
                    models.FloatField(blank=True, db_column="2023-07-05", null=True),
                ),
                (
                    "number_2023_07_11",
                    models.FloatField(blank=True, db_column="2023-07-11", null=True),
                ),
            ],
            options={
                "db_table": "CC2023",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cv2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2019_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2019-03-09", null=True
                    ),
                ),
                (
                    "number_2019_04_12",
                    models.FloatField(blank=True, db_column="2019-04-12", null=True),
                ),
                (
                    "number_2019_05_09",
                    models.FloatField(blank=True, db_column="2019-05-09", null=True),
                ),
                (
                    "number_2019_06_04",
                    models.FloatField(blank=True, db_column="2019-06-04", null=True),
                ),
                (
                    "number_2019_06_14",
                    models.FloatField(blank=True, db_column="2019-06-14", null=True),
                ),
                (
                    "number_2019_06_28",
                    models.FloatField(blank=True, db_column="2019-06-28", null=True),
                ),
                (
                    "number_2019_07_11",
                    models.FloatField(blank=True, db_column="2019-07-11", null=True),
                ),
                (
                    "number_2019_07_18",
                    models.FloatField(blank=True, db_column="2019-07-18", null=True),
                ),
            ],
            options={
                "db_table": "CV2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cv2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2020_02_29",
                    models.BigIntegerField(
                        blank=True, db_column="2020-02-29", null=True
                    ),
                ),
                (
                    "number_2020_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-09", null=True
                    ),
                ),
                (
                    "number_2020_03_20",
                    models.FloatField(blank=True, db_column="2020-03-20", null=True),
                ),
                (
                    "number_2020_04_01",
                    models.FloatField(blank=True, db_column="2020-04-01", null=True),
                ),
                (
                    "number_2020_04_07",
                    models.FloatField(blank=True, db_column="2020-04-07", null=True),
                ),
                (
                    "number_2020_04_16",
                    models.FloatField(blank=True, db_column="2020-04-16", null=True),
                ),
                (
                    "number_2020_04_23",
                    models.FloatField(blank=True, db_column="2020-04-23", null=True),
                ),
                (
                    "number_2020_04_30",
                    models.FloatField(blank=True, db_column="2020-04-30", null=True),
                ),
                (
                    "number_2020_05_07",
                    models.FloatField(blank=True, db_column="2020-05-07", null=True),
                ),
                (
                    "number_2020_05_14",
                    models.FloatField(blank=True, db_column="2020-05-14", null=True),
                ),
                (
                    "number_2020_05_20",
                    models.FloatField(blank=True, db_column="2020-05-20", null=True),
                ),
                (
                    "number_2020_05_28",
                    models.FloatField(blank=True, db_column="2020-05-28", null=True),
                ),
                (
                    "number_2020_06_04",
                    models.FloatField(blank=True, db_column="2020-06-04", null=True),
                ),
                (
                    "number_2020_06_11",
                    models.FloatField(blank=True, db_column="2020-06-11", null=True),
                ),
                (
                    "number_2020_06_18",
                    models.FloatField(blank=True, db_column="2020-06-18", null=True),
                ),
                (
                    "number_2020_06_24",
                    models.FloatField(blank=True, db_column="2020-06-24", null=True),
                ),
                (
                    "number_2020_07_02",
                    models.FloatField(blank=True, db_column="2020-07-02", null=True),
                ),
                (
                    "number_2020_07_07",
                    models.FloatField(blank=True, db_column="2020-07-07", null=True),
                ),
            ],
            options={
                "db_table": "CV2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cv2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2021_02_27",
                    models.BigIntegerField(
                        blank=True, db_column="2021-02-27", null=True
                    ),
                ),
                (
                    "number_2021_03_10",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-10", null=True
                    ),
                ),
                (
                    "number_2021_03_26",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-26", null=True
                    ),
                ),
                (
                    "number_2021_04_07",
                    models.FloatField(blank=True, db_column="2021-04-07", null=True),
                ),
                (
                    "number_2021_04_19",
                    models.FloatField(blank=True, db_column="2021-04-19", null=True),
                ),
                (
                    "number_2021_04_29",
                    models.FloatField(blank=True, db_column="2021-04-29", null=True),
                ),
                (
                    "number_2021_05_05",
                    models.FloatField(blank=True, db_column="2021-05-05", null=True),
                ),
                (
                    "number_2021_05_13",
                    models.FloatField(blank=True, db_column="2021-05-13", null=True),
                ),
                (
                    "number_2021_05_20",
                    models.FloatField(blank=True, db_column="2021-05-20", null=True),
                ),
                (
                    "number_2021_05_27",
                    models.FloatField(blank=True, db_column="2021-05-27", null=True),
                ),
                (
                    "number_2021_06_02",
                    models.FloatField(blank=True, db_column="2021-06-02", null=True),
                ),
                (
                    "number_2021_06_10",
                    models.FloatField(blank=True, db_column="2021-06-10", null=True),
                ),
                (
                    "number_2021_06_17",
                    models.FloatField(blank=True, db_column="2021-06-17", null=True),
                ),
                (
                    "number_2021_06_24",
                    models.FloatField(blank=True, db_column="2021-06-24", null=True),
                ),
                (
                    "number_2021_06_30",
                    models.FloatField(blank=True, db_column="2021-06-30", null=True),
                ),
                (
                    "number_2021_07_09",
                    models.FloatField(blank=True, db_column="2021-07-09", null=True),
                ),
                (
                    "number_2021_07_14",
                    models.FloatField(blank=True, db_column="2021-07-14", null=True),
                ),
                (
                    "number_2021_07_19",
                    models.FloatField(blank=True, db_column="2021-07-19", null=True),
                ),
            ],
            options={
                "db_table": "CV2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cv2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2022_03_15",
                    models.BigIntegerField(
                        blank=True, db_column="2022-03-15", null=True
                    ),
                ),
                (
                    "number_2022_03_31",
                    models.BigIntegerField(
                        blank=True, db_column="2022-03-31", null=True
                    ),
                ),
                (
                    "number_2022_04_08",
                    models.FloatField(blank=True, db_column="2022-04-08", null=True),
                ),
                (
                    "number_2022_04_27",
                    models.FloatField(blank=True, db_column="2022-04-27", null=True),
                ),
                (
                    "number_2022_05_06",
                    models.FloatField(blank=True, db_column="2022-05-06", null=True),
                ),
                (
                    "number_2022_05_11",
                    models.FloatField(blank=True, db_column="2022-05-11", null=True),
                ),
                (
                    "number_2022_05_21",
                    models.FloatField(blank=True, db_column="2022-05-21", null=True),
                ),
                (
                    "number_2022_05_26",
                    models.FloatField(blank=True, db_column="2022-05-26", null=True),
                ),
                (
                    "number_2022_06_03",
                    models.FloatField(blank=True, db_column="2022-06-03", null=True),
                ),
                (
                    "number_2022_06_08",
                    models.FloatField(blank=True, db_column="2022-06-08", null=True),
                ),
                (
                    "number_2022_06_17",
                    models.FloatField(blank=True, db_column="2022-06-17", null=True),
                ),
                (
                    "number_2022_06_23",
                    models.FloatField(blank=True, db_column="2022-06-23", null=True),
                ),
                (
                    "number_2022_06_30",
                    models.FloatField(blank=True, db_column="2022-06-30", null=True),
                ),
                (
                    "number_2022_07_08",
                    models.FloatField(blank=True, db_column="2022-07-08", null=True),
                ),
                (
                    "number_2022_07_13",
                    models.FloatField(blank=True, db_column="2022-07-13", null=True),
                ),
            ],
            options={
                "db_table": "CV2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cv2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2023_03_04",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-04", null=True
                    ),
                ),
                (
                    "number_2023_03_08",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-08", null=True
                    ),
                ),
                (
                    "number_2023_03_14",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-14", null=True
                    ),
                ),
                (
                    "number_2023_03_20",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-20", null=True
                    ),
                ),
                (
                    "number_2023_03_25",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-25", null=True
                    ),
                ),
                (
                    "number_2023_04_01",
                    models.BigIntegerField(
                        blank=True, db_column="2023-04-01", null=True
                    ),
                ),
                (
                    "number_2023_04_11",
                    models.FloatField(blank=True, db_column="2023-04-11", null=True),
                ),
                (
                    "number_2023_04_23",
                    models.FloatField(blank=True, db_column="2023-04-23", null=True),
                ),
                (
                    "number_2023_04_26",
                    models.FloatField(blank=True, db_column="2023-04-26", null=True),
                ),
                (
                    "number_2023_05_01",
                    models.FloatField(blank=True, db_column="2023-05-01", null=True),
                ),
                (
                    "number_2023_05_08",
                    models.FloatField(blank=True, db_column="2023-05-08", null=True),
                ),
                (
                    "number_2023_05_17",
                    models.FloatField(blank=True, db_column="2023-05-17", null=True),
                ),
                (
                    "number_2023_05_24",
                    models.FloatField(blank=True, db_column="2023-05-24", null=True),
                ),
                (
                    "number_2023_05_31",
                    models.FloatField(blank=True, db_column="2023-05-31", null=True),
                ),
                (
                    "number_2023_06_06",
                    models.FloatField(blank=True, db_column="2023-06-06", null=True),
                ),
                (
                    "number_2023_06_12",
                    models.FloatField(blank=True, db_column="2023-06-12", null=True),
                ),
                (
                    "number_2023_06_21",
                    models.FloatField(blank=True, db_column="2023-06-21", null=True),
                ),
                (
                    "number_2023_06_28",
                    models.FloatField(blank=True, db_column="2023-06-28", null=True),
                ),
                (
                    "number_2023_07_05",
                    models.FloatField(blank=True, db_column="2023-07-05", null=True),
                ),
                (
                    "number_2023_07_11",
                    models.FloatField(blank=True, db_column="2023-07-11", null=True),
                ),
            ],
            options={
                "db_table": "CV2023",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={
                "db_table": "django_admin_log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "django_content_type",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={
                "db_table": "django_migrations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={
                "db_table": "django_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ecv2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2019_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2019-03-09", null=True
                    ),
                ),
                (
                    "number_2019_04_12",
                    models.FloatField(blank=True, db_column="2019-04-12", null=True),
                ),
                (
                    "number_2019_05_09",
                    models.FloatField(blank=True, db_column="2019-05-09", null=True),
                ),
                (
                    "number_2019_06_04",
                    models.FloatField(blank=True, db_column="2019-06-04", null=True),
                ),
                (
                    "number_2019_06_14",
                    models.FloatField(blank=True, db_column="2019-06-14", null=True),
                ),
                (
                    "number_2019_06_28",
                    models.FloatField(blank=True, db_column="2019-06-28", null=True),
                ),
                (
                    "number_2019_07_11",
                    models.FloatField(blank=True, db_column="2019-07-11", null=True),
                ),
                (
                    "number_2019_07_18",
                    models.FloatField(blank=True, db_column="2019-07-18", null=True),
                ),
            ],
            options={
                "db_table": "ECV2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ecv2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2020_02_29",
                    models.BigIntegerField(
                        blank=True, db_column="2020-02-29", null=True
                    ),
                ),
                (
                    "number_2020_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-09", null=True
                    ),
                ),
                (
                    "number_2020_03_20",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-20", null=True
                    ),
                ),
                (
                    "number_2020_04_01",
                    models.FloatField(blank=True, db_column="2020-04-01", null=True),
                ),
                (
                    "number_2020_04_07",
                    models.FloatField(blank=True, db_column="2020-04-07", null=True),
                ),
                (
                    "number_2020_04_16",
                    models.FloatField(blank=True, db_column="2020-04-16", null=True),
                ),
                (
                    "number_2020_04_23",
                    models.FloatField(blank=True, db_column="2020-04-23", null=True),
                ),
                (
                    "number_2020_04_30",
                    models.FloatField(blank=True, db_column="2020-04-30", null=True),
                ),
                (
                    "number_2020_05_07",
                    models.FloatField(blank=True, db_column="2020-05-07", null=True),
                ),
                (
                    "number_2020_05_14",
                    models.FloatField(blank=True, db_column="2020-05-14", null=True),
                ),
                (
                    "number_2020_05_20",
                    models.FloatField(blank=True, db_column="2020-05-20", null=True),
                ),
                (
                    "number_2020_05_28",
                    models.FloatField(blank=True, db_column="2020-05-28", null=True),
                ),
                (
                    "number_2020_06_04",
                    models.FloatField(blank=True, db_column="2020-06-04", null=True),
                ),
                (
                    "number_2020_06_11",
                    models.FloatField(blank=True, db_column="2020-06-11", null=True),
                ),
                (
                    "number_2020_06_18",
                    models.FloatField(blank=True, db_column="2020-06-18", null=True),
                ),
                (
                    "number_2020_06_24",
                    models.FloatField(blank=True, db_column="2020-06-24", null=True),
                ),
                (
                    "number_2020_07_02",
                    models.FloatField(blank=True, db_column="2020-07-02", null=True),
                ),
                (
                    "number_2020_07_07",
                    models.FloatField(blank=True, db_column="2020-07-07", null=True),
                ),
            ],
            options={
                "db_table": "ECV2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ecv2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2021_02_27",
                    models.BigIntegerField(
                        blank=True, db_column="2021-02-27", null=True
                    ),
                ),
                (
                    "number_2021_03_10",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-10", null=True
                    ),
                ),
                (
                    "number_2021_03_26",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-26", null=True
                    ),
                ),
                (
                    "number_2021_04_07",
                    models.FloatField(blank=True, db_column="2021-04-07", null=True),
                ),
                (
                    "number_2021_04_19",
                    models.FloatField(blank=True, db_column="2021-04-19", null=True),
                ),
                (
                    "number_2021_04_29",
                    models.FloatField(blank=True, db_column="2021-04-29", null=True),
                ),
                (
                    "number_2021_05_05",
                    models.FloatField(blank=True, db_column="2021-05-05", null=True),
                ),
                (
                    "number_2021_05_13",
                    models.FloatField(blank=True, db_column="2021-05-13", null=True),
                ),
                (
                    "number_2021_05_20",
                    models.FloatField(blank=True, db_column="2021-05-20", null=True),
                ),
                (
                    "number_2021_05_27",
                    models.FloatField(blank=True, db_column="2021-05-27", null=True),
                ),
                (
                    "number_2021_06_02",
                    models.FloatField(blank=True, db_column="2021-06-02", null=True),
                ),
                (
                    "number_2021_06_10",
                    models.FloatField(blank=True, db_column="2021-06-10", null=True),
                ),
                (
                    "number_2021_06_17",
                    models.FloatField(blank=True, db_column="2021-06-17", null=True),
                ),
                (
                    "number_2021_06_24",
                    models.FloatField(blank=True, db_column="2021-06-24", null=True),
                ),
                (
                    "number_2021_06_30",
                    models.FloatField(blank=True, db_column="2021-06-30", null=True),
                ),
                (
                    "number_2021_07_09",
                    models.FloatField(blank=True, db_column="2021-07-09", null=True),
                ),
                (
                    "number_2021_07_14",
                    models.FloatField(blank=True, db_column="2021-07-14", null=True),
                ),
                (
                    "number_2021_07_19",
                    models.FloatField(blank=True, db_column="2021-07-19", null=True),
                ),
            ],
            options={
                "db_table": "ECV2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ecv2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2023_03_04",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-04", null=True
                    ),
                ),
                (
                    "number_2023_03_08",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-08", null=True
                    ),
                ),
                (
                    "number_2023_03_14",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-14", null=True
                    ),
                ),
                (
                    "number_2023_03_20",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-20", null=True
                    ),
                ),
                (
                    "number_2023_03_25",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-25", null=True
                    ),
                ),
                (
                    "number_2023_04_01",
                    models.BigIntegerField(
                        blank=True, db_column="2023-04-01", null=True
                    ),
                ),
                (
                    "number_2023_04_11",
                    models.FloatField(blank=True, db_column="2023-04-11", null=True),
                ),
                (
                    "number_2023_04_23",
                    models.FloatField(blank=True, db_column="2023-04-23", null=True),
                ),
                (
                    "number_2023_04_26",
                    models.FloatField(blank=True, db_column="2023-04-26", null=True),
                ),
                (
                    "number_2023_05_01",
                    models.FloatField(blank=True, db_column="2023-05-01", null=True),
                ),
                (
                    "number_2023_05_08",
                    models.FloatField(blank=True, db_column="2023-05-08", null=True),
                ),
                (
                    "number_2023_05_17",
                    models.FloatField(blank=True, db_column="2023-05-17", null=True),
                ),
                (
                    "number_2023_05_24",
                    models.FloatField(blank=True, db_column="2023-05-24", null=True),
                ),
                (
                    "number_2023_05_31",
                    models.FloatField(blank=True, db_column="2023-05-31", null=True),
                ),
                (
                    "number_2023_06_06",
                    models.FloatField(blank=True, db_column="2023-06-06", null=True),
                ),
                (
                    "number_2023_06_12",
                    models.FloatField(blank=True, db_column="2023-06-12", null=True),
                ),
                (
                    "number_2023_06_21",
                    models.FloatField(blank=True, db_column="2023-06-21", null=True),
                ),
                (
                    "number_2023_06_28",
                    models.FloatField(blank=True, db_column="2023-06-28", null=True),
                ),
                (
                    "number_2023_07_05",
                    models.FloatField(blank=True, db_column="2023-07-05", null=True),
                ),
                (
                    "number_2023_07_11",
                    models.FloatField(blank=True, db_column="2023-07-11", null=True),
                ),
            ],
            options={
                "db_table": "ECV2023",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exg2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2019_03_09",
                    models.FloatField(blank=True, db_column="2019-03-09", null=True),
                ),
                (
                    "number_2019_04_12",
                    models.FloatField(blank=True, db_column="2019-04-12", null=True),
                ),
                (
                    "number_2019_05_09",
                    models.FloatField(blank=True, db_column="2019-05-09", null=True),
                ),
                (
                    "number_2019_06_04",
                    models.FloatField(blank=True, db_column="2019-06-04", null=True),
                ),
                (
                    "number_2019_06_14",
                    models.FloatField(blank=True, db_column="2019-06-14", null=True),
                ),
                (
                    "number_2019_06_28",
                    models.FloatField(blank=True, db_column="2019-06-28", null=True),
                ),
                (
                    "number_2019_07_11",
                    models.FloatField(blank=True, db_column="2019-07-11", null=True),
                ),
                (
                    "number_2019_07_18",
                    models.FloatField(blank=True, db_column="2019-07-18", null=True),
                ),
            ],
            options={
                "db_table": "ExG2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exg2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2_29_2056",
                    models.FloatField(blank=True, db_column="2/29/2056", null=True),
                ),
                (
                    "number_3_9_2057",
                    models.FloatField(blank=True, db_column="3/9/2057", null=True),
                ),
                (
                    "number_3_20_2058",
                    models.FloatField(blank=True, db_column="3/20/2058", null=True),
                ),
                (
                    "number_4_1_2059",
                    models.FloatField(blank=True, db_column="4/1/2059", null=True),
                ),
                (
                    "number_4_7_2060",
                    models.FloatField(blank=True, db_column="4/7/2060", null=True),
                ),
                (
                    "number_4_16_2061",
                    models.FloatField(blank=True, db_column="4/16/2061", null=True),
                ),
                (
                    "number_4_23_2062",
                    models.FloatField(blank=True, db_column="4/23/2062", null=True),
                ),
                (
                    "number_4_30_2063",
                    models.FloatField(blank=True, db_column="4/30/2063", null=True),
                ),
                (
                    "number_5_7_2064",
                    models.FloatField(blank=True, db_column="5/7/2064", null=True),
                ),
                (
                    "number_5_14_2065",
                    models.FloatField(blank=True, db_column="5/14/2065", null=True),
                ),
                (
                    "number_5_20_2066",
                    models.FloatField(blank=True, db_column="5/20/2066", null=True),
                ),
                (
                    "number_5_28_2067",
                    models.FloatField(blank=True, db_column="5/28/2067", null=True),
                ),
                (
                    "number_6_4_2068",
                    models.FloatField(blank=True, db_column="6/4/2068", null=True),
                ),
                (
                    "number_6_11_2069",
                    models.FloatField(blank=True, db_column="6/11/2069", null=True),
                ),
                (
                    "number_6_18_2070",
                    models.FloatField(blank=True, db_column="6/18/2070", null=True),
                ),
                (
                    "number_6_24_2071",
                    models.FloatField(blank=True, db_column="6/24/2071", null=True),
                ),
                (
                    "number_7_2_2072",
                    models.FloatField(blank=True, db_column="7/2/2072", null=True),
                ),
                (
                    "number_7_7_2073",
                    models.FloatField(blank=True, db_column="7/7/2073", null=True),
                ),
            ],
            options={
                "db_table": "ExG2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exg2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2021_02_27",
                    models.FloatField(blank=True, db_column="2021-02-27", null=True),
                ),
                (
                    "number_2021_03_10",
                    models.FloatField(blank=True, db_column="2021-03-10", null=True),
                ),
                (
                    "number_2021_03_26",
                    models.FloatField(blank=True, db_column="2021-03-26", null=True),
                ),
                (
                    "number_2021_04_07",
                    models.FloatField(blank=True, db_column="2021-04-07", null=True),
                ),
                (
                    "number_2021_04_19",
                    models.FloatField(blank=True, db_column="2021-04-19", null=True),
                ),
                (
                    "number_2021_04_29",
                    models.FloatField(blank=True, db_column="2021-04-29", null=True),
                ),
                (
                    "number_2021_05_05",
                    models.FloatField(blank=True, db_column="2021-05-05", null=True),
                ),
                (
                    "number_2021_05_13",
                    models.FloatField(blank=True, db_column="2021-05-13", null=True),
                ),
                (
                    "number_2021_05_20",
                    models.FloatField(blank=True, db_column="2021-05-20", null=True),
                ),
                (
                    "number_2021_05_27",
                    models.FloatField(blank=True, db_column="2021-05-27", null=True),
                ),
                (
                    "number_2021_06_02",
                    models.FloatField(blank=True, db_column="2021-06-02", null=True),
                ),
                (
                    "number_2021_06_10",
                    models.FloatField(blank=True, db_column="2021-06-10", null=True),
                ),
                (
                    "number_2021_06_17",
                    models.FloatField(blank=True, db_column="2021-06-17", null=True),
                ),
                (
                    "number_2021_06_24",
                    models.FloatField(blank=True, db_column="2021-06-24", null=True),
                ),
                (
                    "number_2021_06_30",
                    models.FloatField(blank=True, db_column="2021-06-30", null=True),
                ),
                (
                    "number_2021_07_09",
                    models.FloatField(blank=True, db_column="2021-07-09", null=True),
                ),
                (
                    "number_2021_07_14",
                    models.FloatField(blank=True, db_column="2021-07-14", null=True),
                ),
                (
                    "number_2021_07_19",
                    models.FloatField(blank=True, db_column="2021-07-19", null=True),
                ),
            ],
            options={
                "db_table": "ExG2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exg2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2022_03_15",
                    models.FloatField(blank=True, db_column="2022-03-15", null=True),
                ),
                (
                    "number_2022_03_31",
                    models.FloatField(blank=True, db_column="2022-03-31", null=True),
                ),
                (
                    "number_2022_04_08",
                    models.FloatField(blank=True, db_column="2022-04-08", null=True),
                ),
                (
                    "number_2022_04_27",
                    models.FloatField(blank=True, db_column="2022-04-27", null=True),
                ),
                (
                    "number_2022_05_06",
                    models.FloatField(blank=True, db_column="2022-05-06", null=True),
                ),
                (
                    "number_2022_05_11",
                    models.FloatField(blank=True, db_column="2022-05-11", null=True),
                ),
                (
                    "number_2022_05_21",
                    models.FloatField(blank=True, db_column="2022-05-21", null=True),
                ),
                (
                    "number_2022_05_26",
                    models.FloatField(blank=True, db_column="2022-05-26", null=True),
                ),
                (
                    "number_2022_06_08",
                    models.FloatField(blank=True, db_column="2022-06-08", null=True),
                ),
                (
                    "number_2022_06_17",
                    models.FloatField(blank=True, db_column="2022-06-17", null=True),
                ),
                (
                    "number_2022_06_23",
                    models.FloatField(blank=True, db_column="2022-06-23", null=True),
                ),
                (
                    "number_2022_06_30",
                    models.FloatField(blank=True, db_column="2022-06-30", null=True),
                ),
                (
                    "number_2022_07_08",
                    models.FloatField(blank=True, db_column="2022-07-08", null=True),
                ),
                (
                    "number_2022_07_13",
                    models.FloatField(blank=True, db_column="2022-07-13", null=True),
                ),
            ],
            options={
                "db_table": "ExG2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Exg2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2023_03_04",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-04", null=True
                    ),
                ),
                (
                    "number_2023_03_08",
                    models.FloatField(blank=True, db_column="2023-03-08", null=True),
                ),
                (
                    "number_2023_03_14",
                    models.FloatField(blank=True, db_column="2023-03-14", null=True),
                ),
                (
                    "number_2023_03_20",
                    models.FloatField(blank=True, db_column="2023-03-20", null=True),
                ),
                (
                    "number_2023_03_25",
                    models.FloatField(blank=True, db_column="2023-03-25", null=True),
                ),
                (
                    "number_2023_04_01",
                    models.FloatField(blank=True, db_column="2023-04-01", null=True),
                ),
                (
                    "number_2023_04_11",
                    models.FloatField(blank=True, db_column="2023-04-11", null=True),
                ),
                (
                    "number_2023_04_23",
                    models.FloatField(blank=True, db_column="2023-04-23", null=True),
                ),
                (
                    "number_2023_04_26",
                    models.FloatField(blank=True, db_column="2023-04-26", null=True),
                ),
                (
                    "number_2023_05_01",
                    models.FloatField(blank=True, db_column="2023-05-01", null=True),
                ),
                (
                    "number_2023_05_08",
                    models.FloatField(blank=True, db_column="2023-05-08", null=True),
                ),
                (
                    "number_2023_05_17",
                    models.FloatField(blank=True, db_column="2023-05-17", null=True),
                ),
                (
                    "number_2023_05_24",
                    models.FloatField(blank=True, db_column="2023-05-24", null=True),
                ),
                (
                    "number_2023_05_31",
                    models.FloatField(blank=True, db_column="2023-05-31", null=True),
                ),
                (
                    "number_2023_06_06",
                    models.FloatField(blank=True, db_column="2023-06-06", null=True),
                ),
                (
                    "number_2023_06_12",
                    models.FloatField(blank=True, db_column="2023-06-12", null=True),
                ),
                (
                    "number_2023_06_21",
                    models.FloatField(blank=True, db_column="2023-06-21", null=True),
                ),
                (
                    "number_2023_06_28",
                    models.FloatField(blank=True, db_column="2023-06-28", null=True),
                ),
                (
                    "number_2023_07_05",
                    models.FloatField(blank=True, db_column="2023-07-05", null=True),
                ),
                (
                    "number_2023_07_11",
                    models.FloatField(blank=True, db_column="2023-07-11", null=True),
                ),
            ],
            options={
                "db_table": "ExG2023",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ph2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2019_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2019-03-09", null=True
                    ),
                ),
                (
                    "number_2019_04_12",
                    models.FloatField(blank=True, db_column="2019-04-12", null=True),
                ),
                (
                    "number_2019_05_09",
                    models.FloatField(blank=True, db_column="2019-05-09", null=True),
                ),
                (
                    "number_2019_06_04",
                    models.FloatField(blank=True, db_column="2019-06-04", null=True),
                ),
                (
                    "number_2019_06_14",
                    models.FloatField(blank=True, db_column="2019-06-14", null=True),
                ),
                (
                    "number_2019_06_28",
                    models.FloatField(blank=True, db_column="2019-06-28", null=True),
                ),
                (
                    "number_2019_07_11",
                    models.FloatField(blank=True, db_column="2019-07-11", null=True),
                ),
                (
                    "number_2019_07_18",
                    models.FloatField(blank=True, db_column="2019-07-18", null=True),
                ),
            ],
            options={
                "db_table": "PH2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ph2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2020_02_29",
                    models.BigIntegerField(
                        blank=True, db_column="2020-02-29", null=True
                    ),
                ),
                (
                    "number_2020_03_09",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-09", null=True
                    ),
                ),
                (
                    "number_2020_03_20",
                    models.BigIntegerField(
                        blank=True, db_column="2020-03-20", null=True
                    ),
                ),
                (
                    "number_2020_04_01",
                    models.FloatField(blank=True, db_column="2020-04-01", null=True),
                ),
                (
                    "number_2020_04_07",
                    models.FloatField(blank=True, db_column="2020-04-07", null=True),
                ),
                (
                    "number_2020_04_16",
                    models.FloatField(blank=True, db_column="2020-04-16", null=True),
                ),
                (
                    "number_2020_04_23",
                    models.FloatField(blank=True, db_column="2020-04-23", null=True),
                ),
                (
                    "number_2020_04_30",
                    models.FloatField(blank=True, db_column="2020-04-30", null=True),
                ),
                (
                    "number_2020_05_07",
                    models.FloatField(blank=True, db_column="2020-05-07", null=True),
                ),
                (
                    "number_2020_05_14",
                    models.FloatField(blank=True, db_column="2020-05-14", null=True),
                ),
                (
                    "number_2020_05_20",
                    models.FloatField(blank=True, db_column="2020-05-20", null=True),
                ),
                (
                    "number_2020_05_28",
                    models.FloatField(blank=True, db_column="2020-05-28", null=True),
                ),
                (
                    "number_2020_06_04",
                    models.FloatField(blank=True, db_column="2020-06-04", null=True),
                ),
                (
                    "number_2020_06_11",
                    models.FloatField(blank=True, db_column="2020-06-11", null=True),
                ),
                (
                    "number_2020_06_18",
                    models.FloatField(blank=True, db_column="2020-06-18", null=True),
                ),
                (
                    "number_2020_06_24",
                    models.FloatField(blank=True, db_column="2020-06-24", null=True),
                ),
                (
                    "number_2020_07_02",
                    models.FloatField(blank=True, db_column="2020-07-02", null=True),
                ),
                (
                    "number_2020_07_07",
                    models.FloatField(blank=True, db_column="2020-07-07", null=True),
                ),
            ],
            options={
                "db_table": "PH2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ph2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2021_02_27",
                    models.BigIntegerField(
                        blank=True, db_column="2021-02-27", null=True
                    ),
                ),
                (
                    "number_2021_03_10",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-10", null=True
                    ),
                ),
                (
                    "number_2021_03_26",
                    models.BigIntegerField(
                        blank=True, db_column="2021-03-26", null=True
                    ),
                ),
                (
                    "number_2021_04_07",
                    models.FloatField(blank=True, db_column="2021-04-07", null=True),
                ),
                (
                    "number_2021_04_19",
                    models.FloatField(blank=True, db_column="2021-04-19", null=True),
                ),
                (
                    "number_2021_04_29",
                    models.FloatField(blank=True, db_column="2021-04-29", null=True),
                ),
                (
                    "number_2021_05_05",
                    models.FloatField(blank=True, db_column="2021-05-05", null=True),
                ),
                (
                    "number_2021_05_13",
                    models.FloatField(blank=True, db_column="2021-05-13", null=True),
                ),
                (
                    "number_2021_05_20",
                    models.FloatField(blank=True, db_column="2021-05-20", null=True),
                ),
                (
                    "number_2021_05_27",
                    models.FloatField(blank=True, db_column="2021-05-27", null=True),
                ),
                (
                    "number_2021_06_02",
                    models.FloatField(blank=True, db_column="2021-06-02", null=True),
                ),
                (
                    "number_2021_06_10",
                    models.FloatField(blank=True, db_column="2021-06-10", null=True),
                ),
                (
                    "number_2021_06_17",
                    models.FloatField(blank=True, db_column="2021-06-17", null=True),
                ),
                (
                    "number_2021_06_24",
                    models.FloatField(blank=True, db_column="2021-06-24", null=True),
                ),
                (
                    "number_2021_06_30",
                    models.FloatField(blank=True, db_column="2021-06-30", null=True),
                ),
                (
                    "number_2021_07_09",
                    models.FloatField(blank=True, db_column="2021-07-09", null=True),
                ),
                (
                    "number_2021_07_14",
                    models.FloatField(blank=True, db_column="2021-07-14", null=True),
                ),
                (
                    "number_2021_07_19",
                    models.FloatField(blank=True, db_column="2021-07-19", null=True),
                ),
            ],
            options={
                "db_table": "PH2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ph2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2022_03_15",
                    models.BigIntegerField(
                        blank=True, db_column="2022-03-15", null=True
                    ),
                ),
                (
                    "number_2022_03_31",
                    models.BigIntegerField(
                        blank=True, db_column="2022-03-31", null=True
                    ),
                ),
                (
                    "number_2022_04_08",
                    models.FloatField(blank=True, db_column="2022-04-08", null=True),
                ),
                (
                    "number_2022_04_27",
                    models.FloatField(blank=True, db_column="2022-04-27", null=True),
                ),
                (
                    "number_2022_05_06",
                    models.FloatField(blank=True, db_column="2022-05-06", null=True),
                ),
                (
                    "number_2022_05_11",
                    models.FloatField(blank=True, db_column="2022-05-11", null=True),
                ),
                (
                    "number_2022_05_21",
                    models.FloatField(blank=True, db_column="2022-05-21", null=True),
                ),
                (
                    "number_2022_05_26",
                    models.FloatField(blank=True, db_column="2022-05-26", null=True),
                ),
                (
                    "number_2022_06_03",
                    models.FloatField(blank=True, db_column="2022-06-03", null=True),
                ),
                (
                    "number_2022_06_08",
                    models.FloatField(blank=True, db_column="2022-06-08", null=True),
                ),
                (
                    "number_2022_06_17",
                    models.FloatField(blank=True, db_column="2022-06-17", null=True),
                ),
                (
                    "number_2022_06_23",
                    models.FloatField(blank=True, db_column="2022-06-23", null=True),
                ),
                (
                    "number_2022_06_30",
                    models.FloatField(blank=True, db_column="2022-06-30", null=True),
                ),
                (
                    "number_2022_07_08",
                    models.FloatField(blank=True, db_column="2022-07-08", null=True),
                ),
                (
                    "number_2022_07_13",
                    models.FloatField(blank=True, db_column="2022-07-13", null=True),
                ),
            ],
            options={
                "db_table": "PH2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ph2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "number_2023_03_04",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-04", null=True
                    ),
                ),
                (
                    "number_2023_03_08",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-08", null=True
                    ),
                ),
                (
                    "number_2023_03_14",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-14", null=True
                    ),
                ),
                (
                    "number_2023_03_20",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-20", null=True
                    ),
                ),
                (
                    "number_2023_03_25",
                    models.BigIntegerField(
                        blank=True, db_column="2023-03-25", null=True
                    ),
                ),
                (
                    "number_2023_04_01",
                    models.BigIntegerField(
                        blank=True, db_column="2023-04-01", null=True
                    ),
                ),
                (
                    "number_2023_04_11",
                    models.FloatField(blank=True, db_column="2023-04-11", null=True),
                ),
                (
                    "number_2023_04_23",
                    models.FloatField(blank=True, db_column="2023-04-23", null=True),
                ),
                (
                    "number_2023_04_26",
                    models.FloatField(blank=True, db_column="2023-04-26", null=True),
                ),
                (
                    "number_2023_05_01",
                    models.FloatField(blank=True, db_column="2023-05-01", null=True),
                ),
                (
                    "number_2023_05_08",
                    models.FloatField(blank=True, db_column="2023-05-08", null=True),
                ),
                (
                    "number_2023_05_17",
                    models.FloatField(blank=True, db_column="2023-05-17", null=True),
                ),
                (
                    "number_2023_05_24",
                    models.FloatField(blank=True, db_column="2023-05-24", null=True),
                ),
                (
                    "number_2023_05_31",
                    models.FloatField(blank=True, db_column="2023-05-31", null=True),
                ),
                (
                    "number_2023_06_06",
                    models.FloatField(blank=True, db_column="2023-06-06", null=True),
                ),
                (
                    "number_2023_06_12",
                    models.FloatField(blank=True, db_column="2023-06-12", null=True),
                ),
                (
                    "number_2023_06_21",
                    models.FloatField(blank=True, db_column="2023-06-21", null=True),
                ),
                (
                    "number_2023_06_28",
                    models.FloatField(blank=True, db_column="2023-06-28", null=True),
                ),
                (
                    "number_2023_07_05",
                    models.FloatField(blank=True, db_column="2023-07-05", null=True),
                ),
                (
                    "number_2023_07_11",
                    models.FloatField(blank=True, db_column="2023-07-11", null=True),
                ),
            ],
            options={
                "db_table": "PH2023",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersUserinfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("fristname", models.CharField(db_column="FristName", max_length=100)),
                ("lastname", models.CharField(db_column="LastName", max_length=100)),
            ],
            options={
                "db_table": "users_userinfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsersUsers",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(db_column="Email", max_length=50)),
                ("password", models.CharField(db_column="Password", max_length=50)),
            ],
            options={
                "db_table": "users_users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yield2019",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "yield_field",
                    models.FloatField(blank=True, db_column="yield", null=True),
                ),
                (
                    "number_0_89",
                    models.FloatField(blank=True, db_column="0.89", null=True),
                ),
                (
                    "lbs_acre",
                    models.FloatField(blank=True, db_column="lbs/Acre", null=True),
                ),
            ],
            options={
                "db_table": "Yield2019",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yield2020",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "yield_field",
                    models.FloatField(blank=True, db_column="yield", null=True),
                ),
                (
                    "lbs_acre",
                    models.FloatField(blank=True, db_column="lbs/Acre", null=True),
                ),
            ],
            options={
                "db_table": "Yield2020",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yield2021",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "yield_field",
                    models.FloatField(blank=True, db_column="yield", null=True),
                ),
            ],
            options={
                "db_table": "Yield2021",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yield2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "yield_field",
                    models.FloatField(blank=True, db_column="yield", null=True),
                ),
            ],
            options={
                "db_table": "Yield2022",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Yield2023",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, db_column="FID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "yield_field",
                    models.FloatField(blank=True, db_column="yield", null=True),
                ),
            ],
            options={
                "db_table": "Yield2023",
                "managed": False,
            },
        ),
    ]
