# Generated by Django 5.0.6 on 2024-06-19 20:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shp2019",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=32614),
                ),
            ],
        ),
    ]
