# Generated by Django 5.0.6 on 2024-06-20 16:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton", "0002_shp2019"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cc2022_shp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fid", models.BigIntegerField(null=True)),
                ("d220408", models.FloatField(null=True)),
                ("d220427", models.FloatField(null=True)),
                ("d220506", models.FloatField(null=True)),
                ("d220511", models.FloatField(null=True)),
                ("d220521", models.FloatField(null=True)),
                ("d220526", models.FloatField(null=True)),
                ("d220603", models.FloatField(null=True)),
                ("d220608", models.FloatField(null=True)),
                ("d220617", models.FloatField(null=True)),
                ("d220623", models.FloatField(null=True)),
                ("d220630", models.FloatField(null=True)),
                ("d220708", models.FloatField(null=True)),
                ("d220713", models.FloatField(null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
            ],
        ),
    ]
