# Generated by Django 5.0.6 on 2024-06-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton", "0003_cc2022_shp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cc2022_shp",
            name="id",
        ),
        migrations.AlterField(
            model_name="cc2022_shp",
            name="fid",
            field=models.BigIntegerField(
                blank=True, default=9999, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
