# Generated by Django 5.0.6 on 2024-06-20 18:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotton", "0004_remove_cc2022_shp_id_alter_cc2022_shp_fid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shp2022",
            fields=[
                (
                    "fid",
                    models.BigIntegerField(
                        blank=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=32614),
                ),
            ],
        ),
    ]
